version: 0.0
os: linux
files:
  - source: /index.php
    destination: /var/www/php/
hooks:
  BeforeInstall:
    - location: /scripts/install_dependencies.txt
      timeout: 300
      runas: root
    - location: /scripts/start_server.txt
      timeout: 300
      runas: root
