version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - apt-get install -y unzip
  build:
    commands:
      - zip hello.zip ./index.php
     
artifacts:
  type:
  files:
    - index.php
    - appspec.yml
    - scripts/install-dependencies
    - scripts/start_server
    
  
