version: 0.2

phases:
  Install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get install -y unzip
  build:
    commands:
      - echo Build started on "date"
      - zip hello.zip ./index.html
     
artifacts:
  type:
  files:
    - index.html
    - appspec.yml
    - scripts/install-dependencies
    - scripts/start_server
    
  
