version: 0.2
phases:
  Install:
    runtime-versions:
      nodejs:10
    commands:
      - apt-get install -y unzip
  build:
    commands:
      - echo Build started on "date"
      - zip hellp.zip ./index.html
     
 artifacts:
 type:
 files:
  - index.html
  - appspec.yml
  - scripts/install-dependecies
  - scripts/start_server
  - 1.png
  - aws.gif
  - back.jpg
  
